baseURL = "https://shigebunian.github.io/"
# baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "castanet"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"

# The theme supports menus with up to one submenu per menu item
#
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "contact"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "guest"

[[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "Podcasts"
    identifier = "podcasts"
    url = "books"
    parent = "resources"

[params]
copyright_notice = "Copyright 2018 [ShiGeBuNian](https://shigebunian.github.io)"
description = "The HugoCast is the best podcast you've ever seen. You will learn everything you ever needed to know about [podcasting](https://en.wikipedia.org/wiki/Podcast) from the most inspiring experts to ever show up on the whole internet."
media_prefix = "https://media.blubrry.com/arresteddevops/content.blubrry.com/arresteddevops/"
  [params.feed]
    feed_copyright = "Copyright 2018 ShiGeBuNian" #do not use markdown in this field; it is used in the feed
    itunes_author = "SGBN" #no markdown or HTML
    itunes_summary = "The HugoCast is the best podcast you've ever seen. You will learn everything you ever needed to know about podcasting from the most inspiring experts to ever show up on the whole internet." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Matt Stratton"
    itunes_owner_email = "matt.stratton@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.arresteddevops.com/img/ado-podcast-logo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"

  [params.social]
    twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"

  [params.authors]
    [params.authors.SGBN]
      name	= "Matt Stratton"
      thumbnail = "img/host/matt.png"
      bio = "Matt Stratton is a solutions architect at Chef, where he demonstrates how Chef’s automation platform provides speed and flexibility to clients’ infrastructure. He is devoted to concepts like Continuous Delivery and Infrastructure as Code, and his license plate actually says “DevOps”. He lives in Chicago and has an unhealthy obsession with Doctor Who, Firefly, and Game of Thrones. And whiskey."
    [params.authors.Trevor]
			name = "Trevor Hess"
			thumbnail = "https://www.arresteddevops.com/img/trevor.png"
			bio = ""
				[params.authors.Trevor.social]
					twitter = "trevorghess"
    [params.authors.Bridget]
      name = "Bridget Kromhout"
      thumbnail = "https://www.arresteddevops.com/img/Bridget.png"
      bio = ""
      [params.authors.Bridget.social]
        twitter = "bridgetkromhout"

    [params.links]
      [params.links.ado]
        name = "Arrested DevOps"
        url = "https://www.arresteddevops.com"
      [params.links.ffs]
        name = "Food Fight Show"
        url = "https://foodfightshow.org"
      [params.links.sdt]
        name = "Software Defined Talk"
        url = "https://cote.io/podcasts/sdt/"
    
